# 共通の設定を定義する
spring:
    profiles:
        # デフォルトを明示的に指定する
        # 開発環境以外は環境変数でプロファイルを切り替える
        default: development
        active: development
    messages:
        # メッセージ定義ファイルのパスを含めて設定する
        basename: messages,ValidationMessages
        cache-seconds: -1
        encoding: UTF-8
    jackson:
        # JSONのキーをアンダースコア区切りの文字列にする
        property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
          autoCommit: false
          connectionTimeout: 30000
          idleTimeout: 5000
          maxLifetime: 1800000
          connectionTestQuery: SELECT 1
          minimumIdle: 10
          maximumPoolSize: 30
    batch:
        initializer:
            # ジョブ管理テーブルを自動的に作成する
            enabled: true
        job:
            # 自動的にバッチジョブが起動しないようにする
            enabled: false
doma:
    dialect: mysql
    # 小文字のスネークケースに変換する（firstName → first_name）
    naming: SNAKE_LOWER_CASE
    # SQLファイルをキャッシュする
    sql-file-repository: greedy_cache
    # バルクインサート・アップデートのサイズ
    batch-size: 1000
jmx:
    enabled: false
logging:
    pattern:
        # MDCで設定した値を出力する
        level: "[%X{BATCH_ID}] %5p"


####
# アプリケーションの設定
application:
    processFileLocation: ${java.io.tmpdir}
    mailTemplateLocation: mail/
