# 共通の設定を定義する
spring:
  profiles:
    # デフォルトを明示的に指定する
    # ローカル環境以外は環境変数でプロファイルを切り替える
    default: local
    active: local
  messages:
    # メッセージ定義ファイルのパスを含めて設定する
    basename: messages,ValidationMessages,PropertyNames
    cache-duration: -1
    encoding: UTF-8
  jackson:
    # 日付型をISO形式で出力する
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      autoCommit: false
      connectionTimeout: 30000
      idleTimeout: 5000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
      minimumIdle: 10
      maximumPoolSize: 30
  batch:
    jdbc:
      # ジョブ管理テーブルを自動的に作成しないようにする
      initialize-schema: always
doma:
  dialect: mysql
  # 小文字のスネークケースに変換する（firstName → first_name）
  naming: SNAKE_LOWER_CASE
  # SQLファイルをキャッシュする
  sql-file-repository: greedy_cache
  # バルクインサート・アップデートのサイズ
  batch-size: 1000
  # SQLログの出力形式
  exception-sql-log-type: FORMATTED
  # SQLログのロガー（SLF4J / JUL）
  jdbc-logger: SLF4J
jmx:
  enabled: false
logging:
  pattern:
    # MDCで設定した値を出力する
    level: "[%X{BATCH_ID}] %5p"


####
# アプリケーションの設定
application:
  processFileLocation: build
