spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enable: true
    baseline-on-migrate: true
    placeholder-replacement: false

####
# アプリケーションの設定
application:
  fileUploadLocation: build/sample
  cors:
    allowedHeaders: "Origin, X-Requested-With, Content-Type, Accept, X-XSRF-TOKEN"
    allowedMethods: "POST, GET, PUT, OPTIONS, DELETE"
    allowedOrigins: "*" # CORSを許可するドメイン名を指定する
